script: hill_forced_simulation.py
propagation_model: emulator
nn_ros_model_path: 
inputs:
  - "fuel.fl1h_tac"
  - "fuel.fd_ft"
  - "fuel.Dme_pc"
  - "fuel.SAVcar_ftinv"
  - "fuel.H_BTUlb"
  - "fuel.totMineral_r"
  - "fuel.effectMineral_r"
  - "fuel.fuelDens_lbft3"
  - "fuel.mdOnDry1h_r"
  - "normalWind"
  - "slope"
fuel_type: [2, 6]
domain_width: 1000
domain_height: 1000
horizontal_wind: 20.0
vertical_wind: 0.0
nb_steps: 20
step_size: 10
fire_front: [[10, 550], [50, 500], [10, 450]]
fire_observation: /home/ai4geo/Documents/nn_ros_models/experiments/hill/2024-09-10--12:23:36-RothAnd18/simulation.0.nc

spatial_increment: 0.5
perimeter_resolution: 2 # max distance between two nodes
minimal_propagative_front_depth: 5 # resolution of arrival time matrix
min_speed: 0.0
max_speed: 20.0
relax: 1 # takes 0.2 of the new ROS and 0.8 of the old ROS, to set in function of spatial_increment!
propagation_speed_adjustment_factor: 1
burned_map_layer: 

save_exp: /home/ai4geo/Documents/nn_ros_models/experiments/hill/
logger: True